version: "3"
services:
  cadvisor:
    container_name: monitoring_cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"
    restart: unless-stopped

  prometheus:
    container_name: monitoring_prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes: 
      - "prometheus-data:/prometheus-data:rw"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    privileged: true
    depends_on:
      - cadvisor
    restart: unless-stopped

  grafana:
    container_name: monitoring_grafana
    image: grafana/grafana:9.0.4
    ports:
      - "3001:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes: 
      - "grafana-data:/var/lib/grafana"
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
      - "./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data:
